---
title: "Codebook for week4 assignmnet"
author: "Atul Gunjal"
date: "23 September 2017"
output: html_document
---

# Tidy data set description

In this Codebook, I tried to explain the tiday data set which is generated at the end. 

## The variables in the tidy data

Tidy data contains 180 rows and 77 columns. Each row has averaged variables for each subject and each activity.

## Only all the variables considered are having mean and std string embed in their column name

*	mean: Mean value
*	std: Standard deviation

In short ignore all columns which do not have either eman or std in their name e.g. tBodyAcc-mad()-Y

## The data were averaged based on subject and activity group.

The data collected is about 30 subjects which have done six different activities.  G=hence the tidy daya will have 180 (30*6) rows. 

The Subject column contains teh subject id. The subject id value is betweeen 1 to 30.
Each subject performed six activities. The activities can be:


1.	WALKING
2.	WALKING_UPSTAIRS
3.	WALKING_DOWNSTAIRS
4.	SITTING
5.	STANDING
6.	LAYING



## The tidy data details

The tidy data contain, Six rows for each SUbject. For each Subject have Six activities. For each activities there are 77 observation  (averaged based on activity). 

Thus each row have 79 columns. 77 columns of observations and two for a subject and it's activity. 

The column lables are:

1. "subject" 
2. "activitylabel"
3. "tBodyAcc-mean()-X"
4. "tBodyAcc-mean()-Y"
5. "tBodyAcc-mean()-Z"
6. "tBodyAcc-std()-X"
7. "tBodyAcc-std()-Y"
8. "tBodyAcc-std()-Z"
9. "tGravityAcc-mean()-X"
10. "tGravityAcc-mean()-Y" 
11. "tGravityAcc-mean()-Z"
12. "tGravityAcc-std()-X"
13. "tGravityAcc-std()-Y" 
14. "tGravityAcc-std()-Z" 
15. "tBodyAccJerk-mean()-X" 
16. "tBodyAccJerk-mean()-Y" 
17. "tBodyAccJerk-mean()-Z" 
18. "tBodyAccJerk-std()-X" 
19. "tBodyAccJerk-std()-Y"
20. "tBodyAccJerk-std()-Z"
21. "tBodyGyro-mean()-X"
22. "tBodyGyro-mean()-Y"
23. "tBodyGyro-mean()-Z"
24. "tBodyGyro-std()-X" 
25. "tBodyGyro-std()-Y" 
26. "tBodyGyro-std()-Z" 
27. "tBodyGyroJerk-mean()-X" 
28  "tBodyGyroJerk-mean()-Y" 
29. "tBodyGyroJerk-mean()-Z"
30  "tBodyGyroJerk-std()-X" 
31. "tBodyGyroJerk-std()-Y"
32. "tBodyGyroJerk-std()-Z" 
33. "tBodyAccMag-mean()" 
34. "tBodyAccMag-std()"  
35. "tGravityAccMag-mean()"
36. "tGravityAccMag-std()"
37. "tBodyAccJerkMag-mean()" 
38. "tBodyAccJerkMag-std()"  
39. "tBodyGyroMag-mean()"  
40. "tBodyGyroMag-std()"   
41. "tBodyGyroJerkMag-mean()" 
42. "tBodyGyroJerkMag-std()"  
43. "fBodyAcc-mean()-X"
44. "fBodyAcc-mean()-Y"  
45. "fBodyAcc-mean()-Z"
46. "fBodyAcc-std()-X"  
47. "fBodyAcc-std()-Y"  
48. "fBodyAcc-std()-Z"  
49. "fBodyAcc-meanFreq()-X"
50. "fBodyAcc-meanFreq()-Y" 
51. "fBodyAcc-meanFreq()-Z" 
52. "fBodyAccJerk-mean()-X"
53. "fBodyAccJerk-mean()-Y"
54. "fBodyAccJerk-mean()-Z"
55. "fBodyAccJerk-std()-X" 
56. "fBodyAccJerk-std()-Y"  
57. "fBodyAccJerk-std()-Z"
58. "fBodyAccJerk-meanFreq()-X" 
59. "fBodyAccJerk-meanFreq()-Y"
60. "fBodyAccJerk-meanFreq()-Z"
61. "fBodyGyro-mean()-X" 
62. "fBodyGyro-mean()-Y" 
63. "fBodyGyro-mean()-Z" 
64. "fBodyGyro-std()-X" 
65. "fBodyGyro-std()-Y" 
66. "fBodyGyro-std()-Z"
67. "fBodyGyro-meanFreq()-X" 
68. "fBodyGyro-meanFreq()-Y"
69. "fBodyGyro-meanFreq()-Z" 
70. "fBodyAccMag-mean()" 
71. "fBodyAccMag-std()" 
72. "fBodyAccMag-meanFreq()" 
73. "fBodyBodyAccJerkMag-mean()" 
74. "fBodyBodyAccJerkMag-std()" 
75. "fBodyBodyAccJerkMag-meanFreq()"
76. "fBodyBodyGyroMag-mean()" 
77. "fBodyBodyGyroMag-std()" 
78. "fBodyBodyGyroMag-meanFreq()"  
79. "fBodyBodyGyroJerkMag-mean()"   

